### ISSUE TITLE
Test fails on fresh install with SlimerJS 0.9.5

### ISSUE THREAD

**Issue by ssteinerx** [MangoTools/node-slimerjs#1]
(master)# slimerjs --version
Innophi SlimerJS 0.9.5, Copyright 2012-2015 Laurent Jouanneau & Innophi

 (master)# ./run_tests

testUnexpectedExit
✔ testUnexpectedExit

testbadpath
✔ testSlimerCreatePagePath

testcommandlineoptions
✔ testCommandLineOptions

testcreatepage
Slimer spawn err: TypeError: Cannot read property 'createPage' of undefined
    at /Users/ssteiner/...node-slimerjs/tests/testcreatepage.js:6:11
    at /Users/ssteiner/...node-slimerjs/node-slimerjs.js:146:20
    at null._onTimeout (/Users/ssteiner/...node-slimerjs/node-slimerjs.js:139:18)
    at Timer.listOnTimeout (timers.js:110:15)

FAILURES: Undone tests (or their setups/teardowns):
- testSlimerCreatePage

To fix this, make sure all tests call test.done()

**Comment by ssteinerx** [comment]
Added this:

```
exports.testSlimerCreatePage = function (test) {
  slimer.create(function (error, sl) {
    console.log(error);
```

Got this:

testcreatepage
Slimer immediately exited with: 1
Slimer spawn err: TypeError: Cannot read property 'createPage' of undefined
    at /Users/ssteiner/...node-slimerjs/tests/testcreatepage.js:7:7
    at /Users/ssteiner/...node-slimerjs/node-slimerjs.js:146:20
    at null._onTimeout (/Users/ssteiner/...node-slimerjs/node-slimerjs.js:139:18)
    at Timer.listOnTimeout (timers.js:110:15)

**Comment by ssteinerx** [comment]
NOTE: The test fails on the bundled slimerjs, but succeeds if I pass options to the create function to use my locally installed 0.9.5 slimerjs installation.

```
var slimer = require('../node-slimerjs');

exports.testSlimerCreatePage = function (test) {
  slimer.create(function (err, sl) {
    console.log(err);
    test.ifError(err);
    sl.createPage(function (err, page) {
      test.ifError(err);
      sl.exit();
      test.done();
    });
  }, {
    slimerPath: '/usr/local/bin/slimerjs'
  });
};
```

**Comment by ssteinerx** [comment]
Changed default in node-slimerjs.js to be my installed slimerjs and got much further.

Slimer leaves windows open which must be closed for the test to finish.  Since this is my first experience with this 'not really headless' approach, I'm not sure whether that's normal...

**Comment by billiegoose** [comment]
Is there a good reason to include a copy of SlimerJS in "node-slimerjs" package? I could not get the copy distributed with this package to run on Windows without an error, but if I used the copy provided by the ["slimerjs" package](https://www.npmjs.com/package/slimerjs) then node-slimerjs works for me. Should node-slimerjs package just use the slimerjs package?

**Comment by puzrin** [comment]
See original https://github.com/baudehlo/node-phantom-simple, it now 2.0.0 and includes SlimerJS support with lot of bugfixes.
