### ISSUE TITLE
page.onResourceReceived is not a function

### ISSUE THREAD

**Issue by ghost** [MangoTools/node-slimerjs#11]
Getting this error

``` javascript
Slimer spawn err: TypeError: page.onResourceReceived is not a function
    at /home/somya/ideaProjects/videogenerator/scripts/slimerTest.js:10:18
    at /home/somya/ideaProjects/videogenerator/node_modules/node-slimerjs/node-slimerjs.js:45:30
    at IncomingMessage.<anonymous> (/home/somya/ideaProjects/videogenerator/node_modules/node-slimerjs/node-slimerjs.js:405:17)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

```

Code used is below

``` javascript
slimer.create(function(err,ph) {
        ph.createPage(function(err,page) {
            page.onResourceReceived(function (res) {
                console.log("Recieving ....................................");
            });
            page.set('viewportSize', {width: 1280, height: 720}, function (err) {
                page.open('http://google.com', function () {
                });
            });
        });
    }, {slimerPath: securityConfig.slimerPath});
```

**Comment by bdandy** [comment]
Try to use
```
page.onResourceReceived = function (res) {
                console.log("Recieving ....................................");
            };
```
